grpc:
  server:
    port: 8095
    etcd: "localhost:12379"
    ttl: 15
  client:
    sms:
      target: "etcd:///service/sms"

redis:
  addr: "localhost:6379"

etcd:
  endpoints:
    - "localhost:12379"