db:
  dsn: "root:for.nothing@tcp(localhost:3306)/mercury"

redis:
  addr: "localhost:6379"
  password: "for.nothing"
  db: 1

etcd:
  endpoints:
    - "localhost:12379"

grpc:
  server:
    port: 8091
    etcd: "localhost:12379"
    ttl: 15