db:
  dsn: "root:for.nothing@tcp(localhost:3306)/mercury"

redis:
  addr: "localhost:6379"

etcd:
  endpoints:
    - "localhost:12379"

grpc:
  server:
    port: 9000
    etcd: "localhost:12379"
    ttl: 15
  client:
    user:
      target: "etcd:///service/follow"