version: '3.0'
services:
  mysql-8:
    image: mysql:8.0.20
    container_name: mercury_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: for.nothing
    volumes:
      - ./scripts/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
  redis:
    image: 'bitnami/redis:7.2'
    container_name: mercury_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
  etcd:
    image: 'bitnami/etcd:3.5.11'
    container_name: mercury_etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 12379:2379
  mongo:
    image: mongo:6.0
    container_name: mercury_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: for.nothing
    ports:
      - 27017:27017
  kafka:
    image: 'bitnami/kafka:3.6.1'
    container_name: mercury_kafka
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  prometheus:
    image: prom/prometheus:v2.50.1
    container_name: mercury_prometheus
    volumes:
      - ./scripts/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    command:
      - "--web.enable-remote-write-receiver"
      - "--config.file=/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana-enterprise:10.2.0
    container_name: mercury_grafana
    volumes:
      - ./scripts/grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000
    depends_on:
      - prometheus
  zipkin:
    image: openzipkin/zipkin-slim:2.24
    container_name: mercury_zipkin
    ports:
      - '9411:9411'
  jaeger:
    image: jaegertracing/all-in-one:1.21
    container_name: mercury_jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    container_name: mercury_elasticsearch
    environment:
      - discovery.type=single-node
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms84m -Xmx512m"
    ports:
      - "9200:9200"