version: '3.0'
services:
  mysql-8:
    image: mysql:8.0.20
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: for.nothing
    volumes:
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
  redis:
    image: 'bitnami/redis:7.2'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
  etcd:
    image: 'bitnami/etcd:3.5.11'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379