global:
  external_labels:
    monitor: 'prometheus-monitor'

scrape_configs:
  - job_name: "webook"
    scrape_interval: 5s
    scrape_timeout: 3s
    static_configs:
      # wsl: ifconfig eth0
      - targets: ["host.docker.internal:8081", "172.21.154.21:8081"]