version: '3.0'
services:
  mysql:
    image: mysql:8.0.20
    container_name: mysql-test
    restart: no
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: for.nothing
    volumes:
      - ../../scripts/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "13316:3306"
  redis:
    image: 'bitnami/redis:7.2'
    container_name: redis-test
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '16379:6379'
  kafka:
    image: 'bitnami/kafka:3.6.1'
    container_name: kafka-test
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER