log:
  mode: "prod" # prod, dev

grpc:
  server:
    port: 9001
    etcd: "localhost:12379"
    ttl: 15
  client:
    sms:
      target: "etcd:///service/payment"

redis:
  addr: "localhost:6379"

etcd:
  endpoints:
    - "localhost:12379"
    
db:
  dsn: "root:for.nothing@tcp(localhost:3306)/mercury"
  migrate: true
  
kafka:
  addrs:
    - "localhost:9094"
    
http:
  addr: ":8080"