log:
  mode: "dev" # prod, dev

db:
  dsn: "root:for.nothing@tcp(localhost:3306)/mercury"
  migrate: false

redis:
  addr: "localhost:6379"
  password: "for.nothing"
  db: 1

etcd:
  endpoints:
    - "localhost:12379"

grpc:
  server:
    port: 9002
    etcd: "localhost:12379"
    ttl: 15