db:
  dsn: "root:for.nothing@tcp(127.0.0.1:3306)/webook"

redis:
  addr: "localhost:6379"
  password: "for.nothing"
  db: 1

wechat:
  app_id: "001"
  app_secret: "secret"

web:
  limit:
    interval: 1
    rate: 120
  log:
    req: true
    resp: true

kafka:
  addrs:
    - "localhost:9094"