db:
  dsn: "root:for.nothing@tcp(127.0.0.1:3306)/mercury"

redis:
  addr: "localhost:6379"
  password: "for.nothing"
  db: 1

wechat:
  app_id: "001"
  app_secret: "secret"

web:
  limit:
    interval: 1
    rate: 120
  log:
    req: false
    resp: false

kafka:
  addrs:
    - "localhost:9094"

grpc:
  client:
    interactive:
      target: "etcd:///service/interactive"

etcd:
  endpoints:
    - "localhost:12379"