db:
  dsn: "root:for.nothing@tcp(127.0.0.1:3306)/webook"

redis:
  addr: "localhost:6379"
  password: "for.nothing"
  db: 1

web:
  log:
    req: true
    resp: true

kafka:
  addrs:
    - "localhost:9094"