log:
  mode: "dev" # prod, dev
  # +optional
  # debug : -1, info : 0, warn : 1, error : 2, fatal : 3, panic : 4
  level: "0" 

db:
  dsn: "root:for.nothing@tcp(localhost:3306)/mercury"
  migrate: false

redis:
  addr: "localhost:6379"
  password: "for.nothing"
  db: 1

etcd:
  endpoints:
    - "localhost:12379"

grpc:
  server:
    port: 8091
    etcd: "localhost:12379"
    ttl: 15